// ulissy-codegen/src/rust_emitter.rs
// ULissy Code Generator - Rust Code Emitter
// Version 0.1.1 - FIXED: Added TIT, Breadcrumb, Epoch to single import block

// ============================================================================
// RUST CODE EMITTER
// ============================================================================

pub struct RustEmitter {
    buffer: String,
    indent_level: usize,
    indent_str: String,
}

impl RustEmitter {
    pub fn new() -> Self {
        RustEmitter {
            buffer: String::new(),
            indent_level: 0,
            indent_str: "    ".to_string(), // 4 spaces
        }
    }
    
    pub fn output(&self) -> String {
        self.buffer.clone()
    }
    
    pub fn indent(&mut self) {
        self.indent_level += 1;
    }
    
    pub fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
    
    fn current_indent(&self) -> String {
        self.indent_str.repeat(self.indent_level)
    }
    
    pub fn emit(&mut self, code: &str) {
        self.buffer.push_str(code);
    }
    
    pub fn emit_line(&mut self, code: &str) {
        self.buffer.push_str(&self.current_indent());
        self.buffer.push_str(code);
        self.buffer.push('\n');
    }
    
    pub fn newline(&mut self) {
        self.buffer.push('\n');
    }
    
    pub fn emit_comment(&mut self, comment: &str) {
        self.emit_line(&format!("// {}", comment));
    }
    
    pub fn emit_file_header(&mut self) {
        self.emit_line("// ═══════════════════════════════════════════════════════════════════════════");
        self.emit_line("// AUTO-GENERATED BY ULISSY COMPILER v0.1.0");
        self.emit_line("// DO NOT EDIT MANUALLY - Changes will be overwritten");
        self.emit_line("// ═══════════════════════════════════════════════════════════════════════════");
        self.newline();
        self.emit_line("#![allow(unused_imports)]");
        self.emit_line("#![allow(unused_variables)]");
        self.emit_line("#![allow(dead_code)]");
        self.emit_line("#![allow(non_snake_case)]");
        self.newline();
    }
    
    pub fn emit_imports(&mut self) {
        self.emit_line("// GNS Runtime - all types (single import block)");
        self.emit_line("use gns_runtime::{");
        self.indent();
        
        // Core types
        self.emit_line("// Core types");
        self.emit_line("Duration, Distance, Moment, Percent,");
        self.emit_line("Location, Coordinates, H3Cell,");
        self.emit_line("Battery, BatteryLevel, Sensors,");
        self.emit_line("schedule_every, watch_condition, delay,");
        self.newline();
        
        // Identity types
        self.emit_line("// Identity types");
        self.emit_line("Identity, Keychain, PublicKey, Signature, Hash, Bytes,");
        self.newline();
        
        // Handle types
        self.emit_line("// Handle types");
        self.emit_line("Handle, FacetAddress, Visibility,");
        self.newline();
        
        // Breadcrumb types - FIX #2: Added TIT, Breadcrumb, Epoch here
        self.emit_line("// Breadcrumb types");
        self.emit_line("TIT, Breadcrumb, Epoch, Trajectory,");
        self.newline();
        
        // Messaging types
        self.emit_line("// Messaging types");
        self.emit_line("Message, Envelope, send_encrypted,");
        self.newline();
        
        // Error type
        self.emit_line("// Error type");
        self.emit_line("GnsError,");
        
        self.dedent();
        self.emit_line("};");
    }
}

impl Default for RustEmitter {
    fn default() -> Self {
        Self::new()
    }
}
