// ulissy-codegen/src/generator.rs
// ULissy Code Generator - Main Generation Logic
// Version 0.1.0

use crate::{CodeGenError, GeneratedCode, RustEmitter};
use ulissy_types::{TypedProgram, TypedStatement, TypedStatementKind, TypedExpr, TypedExprKind, Type};
use ulissy_parser::ast::{Literal, BinaryOp, UnaryOp};

// ============================================================================
// CODE GENERATOR
// ============================================================================

pub struct CodeGenerator {
    project_name: String,
    emitter: RustEmitter,
}

impl CodeGenerator {
    pub fn new(project_name: &str) -> Self {
        CodeGenerator {
            project_name: project_name.to_string(),
            emitter: RustEmitter::new(),
        }
    }
    
    pub fn generate(&mut self, program: &TypedProgram) -> Result<GeneratedCode, CodeGenError> {
        // Generate main.rs
        let main_rs = self.generate_main(program)?;
        
        // Generate Cargo.toml
        let cargo_toml = self.generate_cargo_toml();
        
        Ok(GeneratedCode::new(&self.project_name, main_rs, cargo_toml))
    }
    
    fn generate_main(&mut self, program: &TypedProgram) -> Result<String, CodeGenError> {
        self.emitter.emit_file_header();
        self.emitter.emit_imports();
        self.emitter.newline();
        
        // Generate main function
        self.emitter.emit_line("fn main() -> Result<(), GnsError> {");
        self.emitter.indent();
        
        for stmt in &program.statements {
            self.generate_statement(stmt)?;
        }
        
        self.emitter.newline();
        self.emitter.emit_line("Ok(())");
        self.emitter.dedent();
        self.emitter.emit_line("}");
        
        Ok(self.emitter.output())
    }
    
    fn generate_cargo_toml(&self) -> String {
        format!(r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

# AUTO-GENERATED BY ULISSY COMPILER
# Do not edit manually

[dependencies]
gns-crypto-core = {{ path = "../../gns-crypto-core" }}
tokio = {{ version = "1", features = ["full"] }}
thiserror = "1.0"

# GNS Protocol dependencies
ed25519-dalek = "2"
x25519-dalek = "2"
chacha20poly1305 = "0.10"
h3o = "0.6"
sha2 = "0.10"
hkdf = "0.12"
"#, self.project_name)
    }
    
    // ========================================================================
    // STATEMENT GENERATION
    // ========================================================================
    
    fn generate_statement(&mut self, stmt: &TypedStatement) -> Result<(), CodeGenError> {
        match &stmt.kind {
            TypedStatementKind::IdentityDecl { name, init } => {
                self.generate_identity_decl(name, init)
            }
            TypedStatementKind::LetDecl { name, inferred_type, init, .. } => {
                self.generate_let_decl(name, inferred_type, init)
            }
            TypedStatementKind::VarDecl { name, inferred_type, init, .. } => {
                self.generate_var_decl(name, inferred_type, init)
            }
            TypedStatementKind::EveryBlock { interval, condition, body } => {
                self.generate_every_block(interval, condition, body)
            }
            TypedStatementKind::WhenBlock { condition, body } => {
                self.generate_when_block(condition, body)
            }
            TypedStatementKind::SendStatement { recipient, fields } => {
                self.generate_send_statement(recipient, fields)
            }
            TypedStatementKind::ExpressionStatement(expr) => {
                let code = self.generate_expression(expr)?;
                self.emitter.emit_line(&format!("{};", code));
                Ok(())
            }
        }
    }
    
    fn generate_identity_decl(&mut self, name: &str, init: &TypedExpr) -> Result<(), CodeGenError> {
        let init_code = self.generate_expression(init)?;
        self.emitter.emit_line(&format!("let {} = {}?;", name, init_code));
        self.emitter.newline();
        Ok(())
    }
    
    fn generate_let_decl(&mut self, name: &str, ty: &Type, init: &TypedExpr) -> Result<(), CodeGenError> {
        let init_code = self.generate_expression(init)?;
        let type_annotation = self.type_to_rust(ty);
        
        if type_annotation != "auto" {
            self.emitter.emit_line(&format!("let {}: {} = {};", name, type_annotation, init_code));
        } else {
            self.emitter.emit_line(&format!("let {} = {};", name, init_code));
        }
        Ok(())
    }
    
    fn generate_var_decl(&mut self, name: &str, ty: &Type, init: &Option<TypedExpr>) -> Result<(), CodeGenError> {
        let type_annotation = self.type_to_rust(ty);
        
        if let Some(init_expr) = init {
            let init_code = self.generate_expression(init_expr)?;
            if type_annotation != "auto" {
                self.emitter.emit_line(&format!("let mut {}: {} = {};", name, type_annotation, init_code));
            } else {
                self.emitter.emit_line(&format!("let mut {} = {};", name, init_code));
            }
        } else {
            self.emitter.emit_line(&format!("let mut {}: {};", name, type_annotation));
        }
        Ok(())
    }
    
    fn generate_every_block(
        &mut self,
        interval: &TypedExpr,
        condition: &Option<TypedExpr>,
        body: &[TypedStatement],
    ) -> Result<(), CodeGenError> {
        let interval_code = self.generate_expression(interval)?;
        
        self.emitter.emit_comment("ULissy: every block - scheduled task");
        self.emitter.emit_line(&format!(
            "gns_runtime::schedule_every({}, move || {{",
            interval_code
        ));
        self.emitter.indent();
        
        // Add condition check if present
        if let Some(cond) = condition {
            let cond_code = self.generate_expression(cond)?;
            self.emitter.emit_line(&format!("if {} {{", cond_code));
            self.emitter.indent();
        }
        
        // Generate body
        for stmt in body {
            self.generate_statement(stmt)?;
        }
        
        // Close condition if present
        if condition.is_some() {
            self.emitter.dedent();
            self.emitter.emit_line("}");
        }
        
        self.emitter.dedent();
        self.emitter.emit_line("})?;");
        self.emitter.newline();
        
        Ok(())
    }
    
    fn generate_when_block(
        &mut self,
        condition: &TypedExpr,
        body: &[TypedStatement],
    ) -> Result<(), CodeGenError> {
        let cond_code = self.generate_expression(condition)?;
        
        self.emitter.emit_comment("ULissy: when block - conditional trigger");
        self.emitter.emit_line(&format!(
            "gns_runtime::watch_condition(|| {}, move || {{",
            cond_code
        ));
        self.emitter.indent();
        
        for stmt in body {
            self.generate_statement(stmt)?;
        }
        
        self.emitter.dedent();
        self.emitter.emit_line("})?;");
        self.emitter.newline();
        
        Ok(())
    }
    
    fn generate_send_statement(
        &mut self,
        recipient: &TypedExpr,
        fields: &[(String, TypedExpr)],
    ) -> Result<(), CodeGenError> {
        let recipient_code = self.generate_expression(recipient)?;
        
        self.emitter.emit_comment("ULissy: send statement - encrypted message");
        self.emitter.emit_line("{");
        self.emitter.indent();
        
        // Build message struct
        self.emitter.emit_line("let mut message = gns_crypto_core::Message::new();");
        
        for (name, value) in fields {
            let value_code = self.generate_expression(value)?;
            self.emitter.emit_line(&format!(
                "message.set(\"{}\", {});",
                name, value_code
            ));
        }
        
        self.emitter.newline();
        self.emitter.emit_line(&format!(
            "gns_crypto_core::send_encrypted(&{}, message)?;",
            recipient_code
        ));
        
        self.emitter.dedent();
        self.emitter.emit_line("}");
        self.emitter.newline();
        
        Ok(())
    }
    
    // ========================================================================
    // EXPRESSION GENERATION
    // ========================================================================
    
    fn generate_expression(&self, expr: &TypedExpr) -> Result<String, CodeGenError> {
        match &expr.kind {
            TypedExprKind::Literal(lit) => self.generate_literal(lit),
            
            TypedExprKind::Identifier(name) => {
                if name.starts_with('.') {
                    // Enum shorthand: .public -> Visibility::Public
                    let variant = &name[1..];
                    let capitalized = capitalize(variant);
                    Ok(format!("Visibility::{}", capitalized))
                } else {
                    Ok(self.map_identifier(name))
                }
            }
            
            TypedExprKind::Handle(h) => {
                Ok(format!("Handle::from_str(\"@{}\")?", h))
            }
            
            TypedExprKind::FacetAddress { prefix, handle } => {
                Ok(format!(
                    "FacetAddress::new(\"{}\", \"{}\")",
                    prefix, handle
                ))
            }
            
            TypedExprKind::Binary { left, op, right } => {
                let l = self.generate_expression(left)?;
                let r = self.generate_expression(right)?;
                let op_str = self.binary_op_to_rust(op);
                Ok(format!("({} {} {})", l, op_str, r))
            }
            
            TypedExprKind::Unary { op, operand } => {
                let inner = self.generate_expression(operand)?;
                let op_str = match op {
                    UnaryOp::Neg => "-",
                    UnaryOp::Not => "!",
                };
                Ok(format!("({}{})", op_str, inner))
            }
            
            TypedExprKind::Member { object, member } => {
                let obj = self.generate_expression(object)?;
                Ok(format!("{}.{}()", obj, self.map_member(member)))
            }
            
            TypedExprKind::Call { callee, args } => {
                let callee_code = self.generate_expression(callee)?;
                let args_code: Result<Vec<_>, _> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect();
                let args_str = args_code?.join(", ");
                
                // Map special function calls
                let call = match callee_code.as_str() {
                    "print" => format!("println!(\"{{:?}}\", {})", args_str),
                    "breadcrumb" => format!("Breadcrumb::new({})?", args_str),
                    _ => format!("{}({})", callee_code, args_str),
                };
                
                Ok(call)
            }
            
            TypedExprKind::MethodCall { object, method, args } => {
                let obj = self.generate_expression(object)?;
                let args_code: Result<Vec<_>, _> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect();
                let args_str = args_code?.join(", ");
                
                // Map special methods
                let method_rust = self.map_method(method);
                
                if args_str.is_empty() {
                    Ok(format!("{}.{}()", obj, method_rust))
                } else {
                    Ok(format!("{}.{}({})", obj, method_rust, args_str))
                }
            }
            
            TypedExprKind::UnitValue { value, unit } => {
                let val = self.generate_expression(value)?;
                let unit_code = self.map_unit(unit);
                Ok(format!("{}::{}", unit_code, val))
            }
            
            TypedExprKind::Array(elements) => {
                let elems: Result<Vec<_>, _> = elements.iter()
                    .map(|e| self.generate_expression(e))
                    .collect();
                Ok(format!("vec![{}]", elems?.join(", ")))
            }
        }
    }
    
    fn generate_literal(&self, lit: &Literal) -> Result<String, CodeGenError> {
        match lit {
            Literal::Int(n) => Ok(n.to_string()),
            Literal::Float(f) => Ok(format!("{:.6}", f)),
            Literal::String(s) => Ok(format!("\"{}\"", s.replace('"', "\\\""))),
            Literal::Bool(b) => Ok(b.to_string()),
            Literal::Nil => Ok("None".to_string()),
        }
    }
    
    // ========================================================================
    // TYPE MAPPING
    // ========================================================================
    
    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "i64".to_string(),
            Type::Float => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "String".to_string(),
            Type::Nil => "()".to_string(),
            Type::Identity => "Identity".to_string(),
            Type::PublicKey => "PublicKey".to_string(),
            Type::PrivateKey => "PrivateKey".to_string(),
            Type::Signature => "Signature".to_string(),
            Type::Handle => "Handle".to_string(),
            Type::H3Cell => "H3Cell".to_string(),
            Type::Coordinates => "Coordinates".to_string(),
            Type::Distance => "Distance".to_string(),
            Type::Moment => "Moment".to_string(),
            Type::Duration => "Duration".to_string(),
            Type::Hash => "Hash".to_string(),
            Type::BatteryLevel => "BatteryLevel".to_string(),
            Type::Breadcrumb => "Breadcrumb".to_string(),
            Type::Trajectory => "Trajectory".to_string(),
            Type::FacetAddress => "FacetAddress".to_string(),
            Type::Array(inner) => format!("Vec<{}>", self.type_to_rust(inner)),
            Type::Optional(inner) => format!("Option<{}>", self.type_to_rust(inner)),
            Type::Unit => "()".to_string(),
            Type::Any | Type::Unknown => "auto".to_string(),
            Type::Named(n) => n.clone(),
            _ => "auto".to_string(),
        }
    }
    
    // ========================================================================
    // IDENTIFIER/METHOD MAPPING
    // ========================================================================
    
    fn map_identifier(&self, name: &str) -> String {
        match name {
            "Keychain" => "Keychain".to_string(),
            "here" => "Location::current()".to_string(),
            "now" => "Moment::now()".to_string(),
            "battery" => "Battery::level()".to_string(),
            "sensors" => "Sensors::current()".to_string(),
            _ => name.to_string(),
        }
    }
    
    fn map_member(&self, member: &str) -> String {
        match member {
            "primary" => "primary".to_string(),
            "trajectory" => "trajectory".to_string(),
            "count" => "len".to_string(),
            "last" => "last_hash".to_string(),
            "digest" => "digest".to_string(),
            _ => member.to_string(),
        }
    }
    
    fn map_method(&self, method: &str) -> String {
        match method {
            "h3" => "to_h3".to_string(),
            "append" => "append".to_string(),
            "signed" => "sign".to_string(),
            "post" => "post".to_string(),
            "set" => "set".to_string(),
            "request" => "request".to_string(),
            _ => method.to_string(),
        }
    }
    
    fn map_unit(&self, unit: &str) -> String {
        match unit {
            "seconds" => "Duration::from_secs".to_string(),
            "minutes" => "Duration::from_mins".to_string(),
            "hours" => "Duration::from_hours".to_string(),
            "days" => "Duration::from_days".to_string(),
            "meters" => "Distance::meters".to_string(),
            "kilometers" => "Distance::kilometers".to_string(),
            "percent" => "Percent::from".to_string(),
            _ => format!("{}::from", unit),
        }
    }
    
    fn binary_op_to_rust(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Eq => "==",
            BinaryOp::NotEq => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Gt => ">",
            BinaryOp::LtEq => "<=",
            BinaryOp::GtEq => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
            BinaryOp::Range => "..",
            BinaryOp::RangeExclusive => "..",
            BinaryOp::Within => "/* within */",
            BinaryOp::Near => "/* near */",
        }
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
