// ulissy-codegen/src/generator.rs
// ULissy Code Generator - Main Generation Logic
// Version 0.1.0

use crate::{CodeGenError, GeneratedCode, RustEmitter};
use ulissy_types::{TypedProgram, TypedStatement, TypedStatementKind, TypedExpr, TypedExprKind, Type, TypedEnumVariant, TypedObjectField, TypedInterpolatedPart, TypedConfigField, TypedComputedBody};
use ulissy_parser::ast::{Literal, BinaryOp, UnaryOp};

// ============================================================================
// CODE GENERATOR
// ============================================================================

pub struct CodeGenerator {
    project_name: String,
    emitter: RustEmitter,
}

impl CodeGenerator {
    pub fn new(project_name: &str) -> Self {
        CodeGenerator {
            project_name: project_name.to_string(),
            emitter: RustEmitter::new(),
        }
    }
    
    pub fn generate(&mut self, program: &TypedProgram) -> Result<GeneratedCode, CodeGenError> {
        // Generate main.rs
        let main_rs = self.generate_main(program)?;
        
        // Generate Cargo.toml
        let cargo_toml = self.generate_cargo_toml();
        
        Ok(GeneratedCode::new(&self.project_name, main_rs, cargo_toml))
    }
    
    fn generate_main(&mut self, program: &TypedProgram) -> Result<String, CodeGenError> {
        self.emitter.emit_file_header();
        self.emitter.emit_imports();
        self.emitter.newline();
        
        // Generate main function
        self.emitter.emit_line("fn main() -> Result<(), GnsError> {");
        self.emitter.indent();
        
        for stmt in &program.statements {
            self.generate_statement(stmt)?;
        }
        
        self.emitter.newline();
        self.emitter.emit_line("Ok(())");
        self.emitter.dedent();
        self.emitter.emit_line("}");
        
        Ok(self.emitter.output())
    }
    
    fn generate_cargo_toml(&self) -> String {
        format!(r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

# AUTO-GENERATED BY ULISSY COMPILER
# Do not edit manually

[dependencies]
gns-crypto-core = {{ path = "../../gns-crypto-core" }}
tokio = {{ version = "1", features = ["full"] }}
thiserror = "1.0"

# GNS Protocol dependencies
ed25519-dalek = "2"
x25519-dalek = "2"
chacha20poly1305 = "0.10"
h3o = "0.6"
sha2 = "0.10"
hkdf = "0.12"
"#, self.project_name)
    }
    
    // ========================================================================
    // STATEMENT GENERATION
    // ========================================================================
    
    fn generate_statement(&mut self, stmt: &TypedStatement) -> Result<(), CodeGenError> {
        match &stmt.kind {
            TypedStatementKind::IdentityDecl { name, init } => {
                self.generate_identity_decl(name, init)
            }
            TypedStatementKind::LetDecl { name, inferred_type, init, .. } => {
                self.generate_let_decl(name, inferred_type, init)
            }
            TypedStatementKind::VarDecl { name, inferred_type, init, .. } => {
                self.generate_var_decl(name, inferred_type, init)
            }
            TypedStatementKind::EveryBlock { interval, condition, body } => {
                self.generate_every_block(interval, condition, body)
            }
            TypedStatementKind::WhenBlock { condition, body } => {
                self.generate_when_block(condition, body)
            }
            TypedStatementKind::SendStatement { recipient, fields } => {
                self.generate_send_statement(recipient, fields)
            }
            TypedStatementKind::EnumDecl { name, type_params, variants } => {
                self.generate_enum_decl(name, type_params, variants)
            }
            TypedStatementKind::ConfigBlock { fields } => {
                self.generate_config_block(fields)
            }
            TypedStatementKind::ComputedPropertyDecl { name, inferred_type, body } => {
                self.generate_computed_property(name, inferred_type, body)
            }
            TypedStatementKind::ExpressionStatement(expr) => {
                let code = self.generate_expression(expr)?;
                self.emitter.emit_line(&format!("{};", code));
                Ok(())
            }
        }
    }
    
    fn generate_identity_decl(&mut self, name: &str, init: &TypedExpr) -> Result<(), CodeGenError> {
        let init_code = self.generate_expression(init)?;
        self.emitter.emit_line(&format!("let {} = {}?;", name, init_code));
        self.emitter.newline();
        Ok(())
    }
    
    fn generate_let_decl(&mut self, name: &str, ty: &Type, init: &TypedExpr) -> Result<(), CodeGenError> {
        let init_code = self.generate_expression(init)?;
        let type_annotation = self.type_to_rust(ty);
        
        if type_annotation != "auto" {
            self.emitter.emit_line(&format!("let {}: {} = {};", name, type_annotation, init_code));
        } else {
            self.emitter.emit_line(&format!("let {} = {};", name, init_code));
        }
        Ok(())
    }
    
    fn generate_var_decl(&mut self, name: &str, ty: &Type, init: &Option<TypedExpr>) -> Result<(), CodeGenError> {
        let type_annotation = self.type_to_rust(ty);
        
        if let Some(init_expr) = init {
            let init_code = self.generate_expression(init_expr)?;
            if type_annotation != "auto" {
                self.emitter.emit_line(&format!("let mut {}: {} = {};", name, type_annotation, init_code));
            } else {
                self.emitter.emit_line(&format!("let mut {} = {};", name, init_code));
            }
        } else {
            self.emitter.emit_line(&format!("let mut {}: {};", name, type_annotation));
        }
        Ok(())
    }
    
    fn generate_every_block(
        &mut self,
        interval: &TypedExpr,
        condition: &Option<TypedExpr>,
        body: &[TypedStatement],
    ) -> Result<(), CodeGenError> {
        let interval_code = self.generate_expression(interval)?;
        
        self.emitter.emit_comment("ULissy: every block - scheduled task");
        self.emitter.emit_line(&format!(
            "gns_runtime::schedule_every({}, move || {{",
            interval_code
        ));
        self.emitter.indent();
        
        // Add condition check if present
        if let Some(cond) = condition {
            let cond_code = self.generate_expression(cond)?;
            self.emitter.emit_line(&format!("if {} {{", cond_code));
            self.emitter.indent();
        }
        
        // Generate body
        for stmt in body {
            self.generate_statement(stmt)?;
        }
        
        // Close condition if present
        if condition.is_some() {
            self.emitter.dedent();
            self.emitter.emit_line("}");
        }
        
        self.emitter.dedent();
        self.emitter.emit_line("})?;");
        self.emitter.newline();
        
        Ok(())
    }
    
    fn generate_when_block(
        &mut self,
        condition: &TypedExpr,
        body: &[TypedStatement],
    ) -> Result<(), CodeGenError> {
        let cond_code = self.generate_expression(condition)?;
        
        self.emitter.emit_comment("ULissy: when block - conditional trigger");
        self.emitter.emit_line(&format!(
            "gns_runtime::watch_condition(|| {}, move || {{",
            cond_code
        ));
        self.emitter.indent();
        
        for stmt in body {
            self.generate_statement(stmt)?;
        }
        
        self.emitter.dedent();
        self.emitter.emit_line("})?;");
        self.emitter.newline();
        
        Ok(())
    }
    
    fn generate_send_statement(
        &mut self,
        recipient: &TypedExpr,
        fields: &[(String, TypedExpr)],
    ) -> Result<(), CodeGenError> {
        let recipient_code = self.generate_expression(recipient)?;
        
        self.emitter.emit_comment("ULissy: send statement - encrypted message");
        self.emitter.emit_line("{");
        self.emitter.indent();
        
        // Build message struct
        self.emitter.emit_line("let mut message = gns_crypto_core::Message::new();");
        
        for (name, value) in fields {
            let value_code = self.generate_expression(value)?;
            self.emitter.emit_line(&format!(
                "message.set(\"{}\", {});",
                name, value_code
            ));
        }
        
        self.emitter.newline();
        self.emitter.emit_line(&format!(
            "gns_crypto_core::send_encrypted(&{}, message)?;",
            recipient_code
        ));
        
        self.emitter.dedent();
        self.emitter.emit_line("}");
        self.emitter.newline();
        
        Ok(())
    }
    
    /// Generate Rust enum declaration
    fn generate_enum_decl(
        &mut self,
        name: &str,
        type_params: &[String],
        variants: &[TypedEnumVariant],
    ) -> Result<(), CodeGenError> {
        // Emit derives
        self.emitter.emit_line("#[derive(Debug, Clone, PartialEq)]");
        
        // Emit enum declaration with optional type parameters
        if type_params.is_empty() {
            self.emitter.emit_line(&format!("pub enum {} {{", name));
        } else {
            let params = type_params.join(", ");
            self.emitter.emit_line(&format!("pub enum {}<{}> {{", name, params));
        }
        
        self.emitter.indent();
        
        // Emit each variant
        for variant in variants {
            let variant_name = capitalize(&variant.name);
            
            if let Some(associated) = &variant.associated_types {
                if associated.is_empty() {
                    // Empty tuple variant
                    self.emitter.emit_line(&format!("{},", variant_name));
                } else {
                    // Tuple variant: Some(T) or Error(String, i32)
                    let types: Vec<String> = associated.iter()
                        .map(|t| self.type_to_rust(t))
                        .collect();
                    self.emitter.emit_line(&format!("{}({}),", variant_name, types.join(", ")));
                }
            } else {
                // Simple variant: Gps
                self.emitter.emit_line(&format!("{},", variant_name));
            }
        }
        
        self.emitter.dedent();
        self.emitter.emit_line("}");
        self.emitter.newline();
        
        // Generate Default impl if there's a "default" or "none" variant
        self.generate_enum_default_impl(name, type_params, variants)?;
        
        Ok(())
    }
    
    /// Generate Default impl for enums with "default" or "none" variant
    fn generate_enum_default_impl(
        &mut self,
        name: &str,
        type_params: &[String],
        variants: &[TypedEnumVariant],
    ) -> Result<(), CodeGenError> {
        // Find default variant
        let default_variant = variants.iter().find(|v| {
            (v.name == "default" || v.name == "none") && v.associated_types.is_none()
        });
        
        if let Some(variant) = default_variant {
            let variant_name = capitalize(&variant.name);
            
            if type_params.is_empty() {
                self.emitter.emit_line(&format!("impl Default for {} {{", name));
            } else {
                let params = type_params.join(", ");
                self.emitter.emit_line(&format!(
                    "impl<{}> Default for {}<{}> {{",
                    params, name, params
                ));
            }
            
            self.emitter.indent();
            self.emitter.emit_line("fn default() -> Self {");
            self.emitter.indent();
            self.emitter.emit_line(&format!("Self::{}", variant_name));
            self.emitter.dedent();
            self.emitter.emit_line("}");
            self.emitter.dedent();
            self.emitter.emit_line("}");
            self.emitter.newline();
        }
        
        Ok(())
    }
    
    /// Generate a config block as a Rust module with constants
    /// 
    /// ```ulissy
    /// config {
    ///     resolution: 7,
    ///     interval: 10.minutes,
    /// }
    /// ```
    /// 
    /// Generates:
    /// ```rust
    /// mod config {
    ///     pub const RESOLUTION: i64 = 7;
    ///     pub const INTERVAL: Duration = Duration::from_mins(10);
    /// }
    /// ```
    fn generate_config_block(&mut self, fields: &[TypedConfigField]) -> Result<(), CodeGenError> {
        self.emitter.emit_comment("ULissy: config block - module configuration");
        self.emitter.emit_line("mod config {");
        self.emitter.indent();
        
        for field in fields {
            let value_code = self.generate_expression(&field.value)?;
            let const_name = to_screaming_snake_case(&field.name);
            let type_annotation = self.type_to_rust(&field.value.ty);
            
            if type_annotation != "auto" {
                self.emitter.emit_line(&format!(
                    "pub const {}: {} = {};",
                    const_name, type_annotation, value_code
                ));
            } else {
                self.emitter.emit_line(&format!(
                    "pub const {} = {};",
                    const_name, value_code
                ));
            }
        }
        
        self.emitter.dedent();
        self.emitter.emit_line("}");
        self.emitter.newline();
        
        Ok(())
    }
    
    /// Generate a computed property as a Rust function
    /// 
    /// ```ulissy
    /// computed status: Status {
    ///     isActive: collection.running,
    ///     count: total
    /// }
    /// ```
    /// 
    /// Generates:
    /// ```rust
    /// fn status() -> Status {
    ///     Status {
    ///         is_active: collection.running(),
    ///         count: total,
    ///     }
    /// }
    /// ```
    fn generate_computed_property(
        &mut self, 
        name: &str, 
        inferred_type: &Type,
        body: &TypedComputedBody,
    ) -> Result<(), CodeGenError> {
        let rust_name = to_snake_case(name);
        let type_annotation = self.type_to_rust(inferred_type);
        
        self.emitter.emit_comment("ULissy: computed property - reactive value");
        self.emitter.emit_line(&format!("fn {}() -> {} {{", rust_name, type_annotation));
        self.emitter.indent();
        
        match body {
            TypedComputedBody::Expression(expr) => {
                let expr_code = self.generate_expression(expr)?;
                self.emitter.emit_line(&expr_code);
            }
            TypedComputedBody::ObjectFields(fields) => {
                // Generate struct instantiation
                self.emitter.emit_line(&format!("{} {{", type_annotation));
                self.emitter.indent();
                
                for field in fields {
                    let value_code = self.generate_expression(&field.value)?;
                    let rust_field_name = to_snake_case(&field.name);
                    self.emitter.emit_line(&format!("{}: {},", rust_field_name, value_code));
                }
                
                self.emitter.dedent();
                self.emitter.emit_line("}");
            }
        }
        
        self.emitter.dedent();
        self.emitter.emit_line("}");
        self.emitter.newline();
        
        Ok(())
    }
    
    // ========================================================================
    // EXPRESSION GENERATION
    // ========================================================================
    
    fn generate_expression(&self, expr: &TypedExpr) -> Result<String, CodeGenError> {
        match &expr.kind {
            TypedExprKind::Literal(lit) => self.generate_literal(lit),
            
            TypedExprKind::Identifier(name) => {
                if name.starts_with('.') {
                    // Enum shorthand: .public -> Visibility::Public
                    let variant = &name[1..];
                    let capitalized = capitalize(variant);
                    Ok(format!("Visibility::{}", capitalized))
                } else {
                    Ok(self.map_identifier(name))
                }
            }
            
            TypedExprKind::Handle(h) => {
                Ok(format!("Handle::from_str(\"@{}\")?", h))
            }
            
            TypedExprKind::FacetAddress { prefix, handle } => {
                Ok(format!(
                    "FacetAddress::new(\"{}\", \"{}\")",
                    prefix, handle
                ))
            }
            
            TypedExprKind::Binary { left, op, right } => {
                let l = self.generate_expression(left)?;
                let r = self.generate_expression(right)?;
                let op_str = self.binary_op_to_rust(op);
                Ok(format!("({} {} {})", l, op_str, r))
            }
            
            TypedExprKind::Unary { op, operand } => {
                let inner = self.generate_expression(operand)?;
                let op_str = match op {
                    UnaryOp::Neg => "-",
                    UnaryOp::Not => "!",
                };
                Ok(format!("({}{})", op_str, inner))
            }
            
            TypedExprKind::Member { object, member } => {
                let obj = self.generate_expression(object)?;
                Ok(format!("{}.{}()", obj, self.map_member(member)))
            }
            
            TypedExprKind::Call { callee, args } => {
                let callee_code = self.generate_expression(callee)?;
                let args_code: Result<Vec<_>, _> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect();
                let args_str = args_code?.join(", ");
                
                // Map special function calls
                let call = match callee_code.as_str() {
                    "print" => format!("println!(\"{{:?}}\", {})", args_str),
                    "breadcrumb" => format!("Breadcrumb::new({})?", args_str),
                    _ => format!("{}({})", callee_code, args_str),
                };
                
                Ok(call)
            }
            
            TypedExprKind::MethodCall { object, method, args } => {
                let obj = self.generate_expression(object)?;
                let args_code: Result<Vec<_>, _> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect();
                let args_str = args_code?.join(", ");
                
                // Map special methods
                let method_rust = self.map_method(method);
                
                if args_str.is_empty() {
                    Ok(format!("{}.{}()", obj, method_rust))
                } else {
                    Ok(format!("{}.{}({})", obj, method_rust, args_str))
                }
            }
            
            TypedExprKind::UnitValue { value, unit } => {
                let val = self.generate_expression(value)?;
                let unit_code = self.map_unit(unit);
                Ok(format!("{}::{}", unit_code, val))
            }
            
            TypedExprKind::Array(elements) => {
                let elems: Result<Vec<_>, _> = elements.iter()
                    .map(|e| self.generate_expression(e))
                    .collect();
                Ok(format!("vec![{}]", elems?.join(", ")))
            }
            
            // Optional member access: obj?.member
            // Generated as: obj.as_ref().map(|x| x.member())
            TypedExprKind::OptionalMember { object, member } => {
                let obj = self.generate_expression(object)?;
                let member_rust = self.map_member(member);
                
                Ok(format!(
                    "{}.as_ref().map(|__opt| __opt.{}())",
                    obj, member_rust
                ))
            }
            
            // Optional method call: obj?.method(args)
            // Generated as: obj.as_ref().map(|x| x.method(args))
            TypedExprKind::OptionalMethodCall { object, method, args } => {
                let obj = self.generate_expression(object)?;
                let method_rust = self.map_method(method);
                
                let args_code: Result<Vec<_>, _> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect();
                let args_str = args_code?.join(", ");
                
                if args_str.is_empty() {
                    Ok(format!(
                        "{}.as_ref().map(|__opt| __opt.{}())",
                        obj, method_rust
                    ))
                } else {
                    Ok(format!(
                        "{}.as_ref().map(|__opt| __opt.{}({}))",
                        obj, method_rust, args_str
                    ))
                }
            }
            
            // Nil coalescing: expr ?? default
            // Generated as: expr.unwrap_or(default) or expr.unwrap_or_else(|| default)
            TypedExprKind::NilCoalescing { primary, fallback } => {
                let primary_code = self.generate_expression(primary)?;
                let fallback_code = self.generate_expression(fallback)?;
                
                // Use unwrap_or for simple values (literals/identifiers)
                // Use unwrap_or_else for complex expressions (lazy evaluation)
                let is_simple_fallback = matches!(
                    &fallback.kind,
                    TypedExprKind::Literal(_) | TypedExprKind::Identifier(_)
                );
                
                if is_simple_fallback {
                    Ok(format!(
                        "{}.unwrap_or({})",
                        primary_code, fallback_code
                    ))
                } else {
                    Ok(format!(
                        "{}.unwrap_or_else(|| {})",
                        primary_code, fallback_code
                    ))
                }
            }
            
            // Object literal: { x: 10, y: 20 }
            TypedExprKind::ObjectLiteral { fields, type_hint } => {
                self.generate_object_literal(fields, type_hint)
            }
            
            // Interpolated string: "Hello, \(name)!"
            TypedExprKind::InterpolatedString { parts } => {
                self.generate_interpolated_string(parts)
            }
        }
    }
    
    /// Generate Rust code for object literal
    fn generate_object_literal(
        &self,
        fields: &[TypedObjectField],
        type_hint: &Option<String>,
    ) -> Result<String, CodeGenError> {
        if let Some(type_name) = type_hint {
            // Generate named struct instantiation: Point { x: 10, y: 20 }
            let mut field_inits = Vec::new();
            
            for field in fields {
                let value_code = self.generate_expression(&field.value)?;
                // Convert camelCase to snake_case for Rust
                let rust_field_name = to_snake_case(&field.name);
                field_inits.push(format!("{}: {}", rust_field_name, value_code));
            }
            
            Ok(format!("{} {{ {} }}", type_name, field_inits.join(", ")))
        } else {
            // Generate anonymous object as HashMap
            let mut inserts = Vec::new();
            
            for field in fields {
                let value_code = self.generate_expression(&field.value)?;
                inserts.push(format!(
                    "(\"{}\".to_string(), Box::new({}) as Box<dyn std::any::Any>)",
                    field.name, value_code
                ));
            }
            
            Ok(format!(
                "std::collections::HashMap::from([{}])",
                inserts.join(", ")
            ))
        }
    }
    
    /// Generate Rust code for interpolated string
    /// ULissy: "Hello, \(name)!" → Rust: format!("Hello, {}!", name)
    fn generate_interpolated_string(
        &self,
        parts: &[TypedInterpolatedPart],
    ) -> Result<String, CodeGenError> {
        let mut format_string = String::new();
        let mut args = Vec::new();
        
        for part in parts {
            match part {
                TypedInterpolatedPart::Literal(s) => {
                    // Escape braces for format!()
                    let escaped = s
                        .replace('{', "{{")
                        .replace('}', "}}");
                    format_string.push_str(&escaped);
                }
                TypedInterpolatedPart::Expression(expr) => {
                    // Add placeholder to format string
                    format_string.push_str("{}");
                    
                    // Generate expression and add to args
                    let expr_code = self.generate_expression(expr)?;
                    args.push(expr_code);
                }
            }
        }
        
        // Generate the format!() call
        if args.is_empty() {
            // No interpolations, just a plain string
            Ok(format!("\"{}\".to_string()", format_string))
        } else {
            Ok(format!(
                "format!(\"{}\", {})",
                format_string,
                args.join(", ")
            ))
        }
    }
    
    fn generate_literal(&self, lit: &Literal) -> Result<String, CodeGenError> {
        match lit {
            Literal::Int(n) => Ok(n.to_string()),
            Literal::Float(f) => Ok(format!("{:.6}", f)),
            Literal::String(s) => Ok(format!("\"{}\"", s.replace('"', "\\\""))),
            Literal::Bool(b) => Ok(b.to_string()),
            Literal::Nil => Ok("None".to_string()),
        }
    }
    
    // ========================================================================
    // TYPE MAPPING
    // ========================================================================
    
    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "i64".to_string(),
            Type::Float => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "String".to_string(),
            Type::Nil => "()".to_string(),
            Type::Identity => "Identity".to_string(),
            Type::PublicKey => "PublicKey".to_string(),
            Type::PrivateKey => "PrivateKey".to_string(),
            Type::Signature => "Signature".to_string(),
            Type::Handle => "Handle".to_string(),
            Type::H3Cell => "H3Cell".to_string(),
            Type::Coordinates => "Coordinates".to_string(),
            Type::Distance => "Distance".to_string(),
            Type::Moment => "Moment".to_string(),
            Type::Duration => "Duration".to_string(),
            Type::Hash => "Hash".to_string(),
            Type::BatteryLevel => "BatteryLevel".to_string(),
            Type::Breadcrumb => "Breadcrumb".to_string(),
            Type::Trajectory => "Trajectory".to_string(),
            Type::FacetAddress => "FacetAddress".to_string(),
            Type::Array(inner) => format!("Vec<{}>", self.type_to_rust(inner)),
            Type::Optional(inner) => format!("Option<{}>", self.type_to_rust(inner)),
            Type::Unit => "()".to_string(),
            Type::Any | Type::Unknown => "auto".to_string(),
            Type::Named(n) => n.clone(),
            _ => "auto".to_string(),
        }
    }
    
    // ========================================================================
    // IDENTIFIER/METHOD MAPPING
    // ========================================================================
    
    fn map_identifier(&self, name: &str) -> String {
        match name {
            "Keychain" => "Keychain".to_string(),
            "here" => "Location::current()".to_string(),
            "now" => "Moment::now()".to_string(),
            "battery" => "Battery::level()".to_string(),
            "sensors" => "Sensors::current()".to_string(),
            _ => name.to_string(),
        }
    }
    
    fn map_member(&self, member: &str) -> String {
        match member {
            "primary" => "primary".to_string(),
            "trajectory" => "trajectory".to_string(),
            "count" => "len".to_string(),
            "last" => "last_hash".to_string(),
            "digest" => "digest".to_string(),
            _ => member.to_string(),
        }
    }
    
    fn map_method(&self, method: &str) -> String {
        match method {
            "h3" => "to_h3".to_string(),
            "append" => "append".to_string(),
            "signed" => "sign".to_string(),
            "post" => "post".to_string(),
            "set" => "set".to_string(),
            "request" => "request".to_string(),
            _ => method.to_string(),
        }
    }
    
    fn map_unit(&self, unit: &str) -> String {
        match unit {
            "seconds" => "Duration::from_secs".to_string(),
            "minutes" => "Duration::from_mins".to_string(),
            "hours" => "Duration::from_hours".to_string(),
            "days" => "Duration::from_days".to_string(),
            "meters" => "Distance::meters".to_string(),
            "kilometers" => "Distance::kilometers".to_string(),
            "percent" => "Percent::from".to_string(),
            _ => format!("{}::from", unit),
        }
    }
    
    fn binary_op_to_rust(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Eq => "==",
            BinaryOp::NotEq => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Gt => ">",
            BinaryOp::LtEq => "<=",
            BinaryOp::GtEq => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
            BinaryOp::Range => "..",
            BinaryOp::RangeExclusive => "..",
            BinaryOp::Within => "/* within */",
            BinaryOp::Near => "/* near */",
        }
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

/// Convert camelCase to snake_case
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

/// Convert camelCase to SCREAMING_SNAKE_CASE
fn to_screaming_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c);
        } else {
            result.push(c.to_uppercase().next().unwrap());
        }
    }
    result
}
