// ulissy-codegen/src/rust_emitter.rs
// ULissy Code Generator - Rust Code Emitter
// Version 0.1.0

// ============================================================================
// RUST CODE EMITTER
// ============================================================================

pub struct RustEmitter {
    buffer: String,
    indent_level: usize,
    indent_str: String,
}

impl RustEmitter {
    pub fn new() -> Self {
        RustEmitter {
            buffer: String::new(),
            indent_level: 0,
            indent_str: "    ".to_string(), // 4 spaces
        }
    }
    
    pub fn output(&self) -> String {
        self.buffer.clone()
    }
    
    pub fn indent(&mut self) {
        self.indent_level += 1;
    }
    
    pub fn dedent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
    
    fn current_indent(&self) -> String {
        self.indent_str.repeat(self.indent_level)
    }
    
    pub fn emit(&mut self, code: &str) {
        self.buffer.push_str(code);
    }
    
    pub fn emit_line(&mut self, code: &str) {
        self.buffer.push_str(&self.current_indent());
        self.buffer.push_str(code);
        self.buffer.push('\n');
    }
    
    pub fn newline(&mut self) {
        self.buffer.push('\n');
    }
    
    pub fn emit_comment(&mut self, comment: &str) {
        self.emit_line(&format!("// {}", comment));
    }
    
    pub fn emit_file_header(&mut self) {
        self.emit_line("// ═══════════════════════════════════════════════════════════════════════════");
        self.emit_line("// AUTO-GENERATED BY ULISSY COMPILER v0.1.0");
        self.emit_line("// DO NOT EDIT MANUALLY - Changes will be overwritten");
        self.emit_line("// ═══════════════════════════════════════════════════════════════════════════");
        self.newline();
        self.emit_line("#![allow(unused_imports)]");
        self.emit_line("#![allow(unused_variables)]");
        self.emit_line("#![allow(dead_code)]");
        self.newline();
    }
    
    pub fn emit_imports(&mut self) {
        self.emit_line("// GNS Crypto Core imports");
        self.emit_line("use gns_crypto_core::{");
        self.indent();
        self.emit_line("Identity, Keychain, Breadcrumb, Trajectory,");
        self.emit_line("H3Cell, Hash, Signature, PublicKey,");
        self.emit_line("Handle, FacetAddress, GnsError,");
        self.emit_line("Message, Envelope, Visibility,");
        self.dedent();
        self.emit_line("};");
        self.newline();
        
        self.emit_line("// Runtime support");
        self.emit_line("use gns_runtime::{");
        self.indent();
        self.emit_line("Duration, Distance, Moment, Percent,");
        self.emit_line("Location, Battery, Sensors,");
        self.dedent();
        self.emit_line("};");
    }
}

impl Default for RustEmitter {
    fn default() -> Self {
        Self::new()
    }
}
